### ISSUE TITLE
How to parse real-time chromium pages

### ISSUE THREAD

**Issue by Kghostpassby** [sarperavci/CloudflareBypassForScraping#2] opened 2024-02-26 03:36 UTC
I've used your program and he did help me bypass cloudflare's panel validation, which I must say is amazing, but I'm having a problem now, I want to rely on the program to parse the html of the site, but it seems that many third party libraries don't support parsing chromium, so if you have a solution to this problem, please be sure to let me know.

Ps. My English is not very good, so this article is translated by google, sorry if I have offended you!

**Comment by sarperavci** [comment] 2024-02-26 09:48
Hi,
You can get the page content with the `html` attribute.

`html_content = driver.html`

Than you can process the html with the beautifulsoup library.

For further information, you can always visit the very detailed [documentation page of the library](https://g1879.gitee.io/drissionpagedocs/ChromiumPage/get_page_info/#-html). (use translate)

**Comment by Kghostpassby** [comment] 2024-02-27 01:35
Wow. You've done me a huge favor. Thank you.

**Comment by sarperavci** [comment] 2024-02-27 09:52
Seems like the issue is solved. I'm closing the thread.

**Closed** 2024-02-27 09:52 UTC
